image: archlinux
packages:
  - go
  - postgresql
  - sudo
sources:
  - https://github.com/mariusor/littr.go
tasks:
  - postgres: |
      sudo -u postgres -- initdb --locale en_US.UTF-8 -E UTF8 -D /var/lib/postgres/data
      sudo systemctl start postgresql.service
  - build: |
      cd littr.go
      export GO111MODULE=on
      cp .env.example .env
      make all
  - tests: |
      cd littr.go
      export GO111MODULE=on
      make tests
