image: archlinux
packages:
  - go
sources:
  - https://github.com/mariusor/littr.go
tasks:
  - build: |
      cd littr.go
      export GO111MODULE=on
      cp .env.example .env
      make test
      make all
