image: archlinux
packages:
  - go
  - postgresql
  - docker
sources:
  - https://github.com/mariusor/littr.go
environment:
  GO111MODULE: 'on'
tasks:
  - setup: |
      set +x
      sudo -u postgres -- initdb --locale en_US.UTF-8 -E UTF8 -D /var/lib/postgres/data
      sudo systemctl start postgresql.service
      sudo systemctl start docker.service
      cd littr.go && go mod download
  - versions: |
      set +x
      $(readlink -f /proc/$$/exe) --version | head -n1
      docker --version
      pg_ctl --version
      make --version | head -n1
      go version
  - build: |
      cd littr.go
      make all
  - tests: |
      cd littr.go
      make -s tests
  - docker: |
      cd littr.go
      make -s images
