version: "3.8"
services:
  fedbox:
    image:
      - fedbox/app:${ENV}
      - quay.io/fedbox/fedbox:${ENV}
    command: /bin/fedbox --env ${ENV}
    expose:
      - 4000
    environment:
      - ENV=${ENV}
      - LISTEN=:4000
    volumes:
      - /tmp:/storage
    networks:
      - default
  bootstrap:
    image: quay.io/fedbox/fedbox:${ENV}
    command: /bin/ctl --env ${ENV} bootstrap
    volumes:
      - /tmp:/storage
    depends_on:
      - fedbox
  add_app:
    image: quay.io/fedbox/fedbox:${ENV}
    command: /bin/ctl --env ${ENV} oauth client add --redirectUri http://brutalinks.git/auth/fedbox/callback
    volumes:
      - /tmp:/storage
    depends_on:
      - bootstrap
  lb:
    env_file: ./.env
    image: caddy
    ports:
      - 80:80
      - 443:443
    links:
    - app
    volumes:
    -  ./Caddyfile:/etc/caddy/Caddyfile
    environment:
    - VARNISH_BACKEND_ADDRESS=app
    - VARNISH_BACKEND_PORT=${PORT}
    networks:
      - default
  app:
    env_file: ./.env
    image: quay.io/fedbox/littr:${ENV}
    depends_on:
    - add_app
    links:
    - fedbox
#    - redis
#    - es
    command: /bin/littr -host ${HOSTNAME} -port ${PORT} -env ${ENV}
    networks:
      - default

networks:
  default:
    internal: true
