version: "3"
services:
  fedbox:
    env_file: ./.env
    image: ${HOSTNAME}/fedbox:${ENV}
    build:
      context: fedbox
      dockerfile: ./Dockerfile
      args:
        ENV: ${ENV}
        HOSTNAME: ${HOSTNAME}
    command: fedbox --env ${ENV}
  lb:
    env_file: ./.env
    image: ${HOSTNAME}/lb:${ENV}
    build:
      context: varnish
      dockerfile: ./Dockerfile
      args:
        LISTEN: ${LISTEN}
        HOSTNAME: ${HOSTNAME}
    ports:
      - 80:80
    links:
    - app
    environment:
    - VARNISH_BACKEND_ADDRESS=app
    - VARNISH_BACKEND_PORT=${PORT}
  ssl:
    env_file: ./.env
    image: ${HOSTNAME}/ssl:${ENV}
    build:
      context: hitch
      dockerfile: ./Dockerfile
      args:
        LISTEN: ${LISTEN}
        HOSTNAME: ${HOSTNAME}
    ports:
    - 443:443
    depends_on:
    - lb
    links:
    - lb
    environment:
    - HITCH_BACKEND_ADDRESS=lb
    - HITCH_BACKEND_PORT=6081
    networks:
      default:
        aliases:
          - ${HOSTNAME}
  app:
    env_file: ./.env
    image: ${HOSTNAME}/app:${ENV}
#    depends_on:
#    links:
#    - redis
#    - es
    build:
      context: app
      dockerfile: ./Dockerfile
      args:
        ENV: ${ENV}
        LISTEN: ${LISTEN}
        HOSTNAME: ${HOSTNAME}
    command: app -host ${HOSTNAME} -port ${PORT} -env ${ENV}
