version: "3"
services:
  db:
    env_file: ./.env
    image: postgres:10-alpine
    volumes:
    - /tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
### Uncomment to enable DB persistence
    command: postgres -c log_connections=on -c logging_collector=on -c log_destination=stderr

#  redis:
#    restart: always
#    image: redis:4.0-alpine
#    ports:
#    - 6379:6379
#### Uncomment to enable REDIS persistence
#    volumes:
#    - /tmp/redis:/data
#
#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
#    environment:
#    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#### Uncomment to enable ES persistence
#    volumes:
#    - /tmp/es:/usr/share/elasticsearch/data

  lb:
    env_file: ./.env
    build:
      context: varnish
      dockerfile: ./Dockerfile
      args:
        LISTEN: ${LISTEN}
        HOSTNAME: ${HOSTNAME}
    ports:
    - 80:80
    - 6081:6081
    links:
    - app
    depends_on:
    - app
    environment:
    - VARNISH_BACKEND_ADDRESS=app
    - VARNISH_BACKEND_PORT=${LISTEN}

  ssl:
    env_file: ./.env
    build:
      context: hitch
      dockerfile: ./Dockerfile
      args:
        LISTEN: ${LISTEN}
        HOSTNAME: ${HOSTNAME}
    ports:
    - 443:443
    volumes:
    - ./littr.git.pem:/etc/ssl/hitch/littr.pem
    depends_on:
    - lb
    links:
    - lb
    environment:
    - HITCH_BACKEND_ADDRESS=lb
    - HITCH_BACKEND_PORT=6081

  bootstrap:
    env_file: ./.env
    image: bootstrap:${ENV}
    depends_on:
    - db
    links:
    - db
    build:
      context: bootstrap
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  app:
    env_file: ./.env
    image: web_app:${ENV}
    depends_on:
    - db
#      - bootstrap
#      - ssl
    links:
    - db
#    - redis
#    - es
    build:
      context: app
      dockerfile: ./Dockerfile
      args:
        ENV: ${ENV}
        LISTEN: ${LISTEN}
        HOSTNAME: ${HOSTNAME}
        PORT: 40001
    command: app -host ${HOSTNAME} -port 3000
